// Port real circuit outlines from the Godot ApexDuo_Prototype/track_shapes.gd into a flat
// ApexWeb registry (src/track_shapes.js), and validate that each renders fold-free.
import { readFileSync, writeFileSync } from "fs";
import { buildCenterline, splinePath, ribbonEdges, bounds, pointAt } from "../src/geom3d.js";

const gd = readFileSync(new URL("../../ApexDuo_Prototype/track_shapes.gd", import.meta.url), "utf8");
const re = /"([^"]+)":\s*PackedVector2Array\(\[([\s\S]*?)\]\)/g;
const shapes = {};
let m;
while ((m = re.exec(gd)) !== null) {
  const nums = [...m[2].matchAll(/Vector2\(\s*([\d.]+)\s*,\s*([\d.]+)\s*\)/g)].flatMap((v) => [parseFloat(v[1]), parseFloat(v[2])]);
  if (nums.length >= 12) shapes[m[1]] = nums;
}
const names = Object.keys(shapes);
console.error(`parsed ${names.length}: ${names.join(", ")}`);

// validate: the curvature clamp should give every shape 0 folds
const WORLD = 120, HALF_W = 3.8, STEPS = 320;
let bad = 0;
for (const name of names) {
  const cl = buildCenterline(splinePath(shapes[name]));
  const b = bounds(cl), HW_N = HALF_W / (WORLD / b.size);
  const { left, right } = ribbonEdges(cl, HW_N, STEPS);
  let folds = 0;
  for (const edge of [left, right]) for (let k = 0; k < STEPS; k++) {
    const a = edge[k], c = edge[(k + 1) % STEPS], f = (k + 0.5) / STEPS, p0 = pointAt(cl, f - 1e-3), p1 = pointAt(cl, f + 1e-3);
    if ((c[0] - a[0]) * (p1[0] - p0[0]) + (c[1] - a[1]) * (p1[1] - p0[1]) < -1e-9) folds++;
  }
  if (folds) { console.error(`  WARN ${name}: ${folds} folds`); bad++; }
}
console.error(bad ? `${bad} shapes with folds` : "all shapes fold-free");

const body = names.map((n) => `  ${JSON.stringify(n)}: [${shapes[n].map((x) => +x.toFixed(4)).join(",")}],`).join("\n");
const out = `// ApexWeb/src/track_shapes.js — real circuit outlines (normalized 0..1, flat [x0,y0,...]).
// Ported from ApexDuo_Prototype/track_shapes.gd (f1-circuits-svg by ROY Jules, CC BY 4.0:
// https://github.com/julesr0y/f1-circuits-svg). ${names.length} circuits, 120 pts each. The 3D + 2D
// race views pick one per race via pickTrack(seed); the deterministic sim is unaffected (it races
// abstract sectors). Generated by tools/port_shapes.mjs — do not hand-edit.
import { mix32 } from "./rng.js";

export const TRACK_SHAPES = {
${body}
};

export const TRACK_NAMES = Object.keys(TRACK_SHAPES);

// Deterministic circuit pick from the shared race seed (host & client derive the same one).
export function pickTrack(seed) {
  return TRACK_NAMES[mix32((seed >>> 0) || 1) % TRACK_NAMES.length];
}
`;
writeFileSync(new URL("../src/track_shapes.js", import.meta.url), out);
console.error(`wrote src/track_shapes.js (${(out.length / 1024).toFixed(0)} KB)`);
